name: gen_crm
description: A new Flutter application.
publish_to: 'none'
version: 2.3.6+236
#versionNew

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  intl: any

  flutter_dotenv: ^5.0.2
  flutter_bloc: ^7.0.0
  keyboard_dismisser: ^2.0.0
  community_material_icon: ^5.9.55
  cached_network_image: ^3.2.0
  formz: ^0.4.1
  equatable: ^2.0.3
  double_back_to_close_app: ^2.1.0
  url_launcher: ^6.0.17
  nb_utils: ^4.4.10
  get: ^4.6.1
  get_it: ^7.2.0
  logger: ^1.1.0
  flash: ^2.0.3+1
  dio: ^4.0.4
  lottie: ^1.2.1
  shared_preferences: ^2.0.11
  json_annotation: ^4.4.0
  retrofit: ^3.3.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  retrofit_generator:  4.2.0 #flutter pub run build_runner build --delete-conflicting-outputs
  http: ^0.13.4
  meta: ^1.7.0
  flutter_html: ^3.0.0-alpha.6
  flutter_svg: ^2.0.4
  hexcolor: ^2.0.6
  image_picker: ^0.8.5
  path_provider: ^2.0.9
  multi_select_flutter: ^4.1.2
  flutter_keyboard_visibility: ^5.4.0
  tiengviet: ^0.5.0
  file_picker: ^5.2.6
  dropdown_button2: 1.7.2
  syncfusion_flutter_datepicker: ^20.2.49
  firebase_messaging: ^14.4.0
  firebase_core: ^2.9.0
  flutter_local_notifications: ^13.0.0
  local_auth: 2.1.6
  permission_handler: ^10.2.0
  rxdart: ^0.27.7
  quiver: ^3.2.1
  photo_view: ^0.14.0
  dartx: ^1.1.0
  flutter_pitel_voip: ^1.0.7+7
  flutter_riverpod: ^2.4.9
  qr_code_scanner: ^1.0.1
  is_lock_screen: ^2.0.0
  geolocator: 9.0.2
  geocoding: 2.1.0
  wakelock: ^0.6.2
  flutter_expandable_fab: 1.7.1
  signature: 5.3.2
  location: 4.4.0
  pretty_dio_logger: any
  flutter_webrtc: 0.9.40 #cÃ¡ch fix https://pub.dev/packages/flutter_pitel_voip
  watcher: 1.0.2
  flutter_easyloading: ^3.0.5
  package_info_plus: ^3.1.2
  currency_text_input_formatter:

dependency_overrides:
  watcher: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 600

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic

  assets:
    - assets/.env
    - assets/lottie/
    - assets/images/
    - assets/fonts/
    - assets/icons/
